//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trichromatic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public ProductGroup()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int SSID { get; set; }
        public int SortOrder { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual SubSection SubSection { get; set; }
    }
}
